/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package good.api;

import good.api.web.WebServerConfig;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {
    public static void main(String[] args) {
        SpringApplication.run(WebServerConfig.class, args);
    }
}
