version: '3.8'

services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    networks:
      - postgres_network

  pg_admin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "44523:80"
    depends_on:
      - postgres_db
    networks:
      - postgres_network

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge
